[configuration]
    # Откуда загружать конфигурацию. Может быть три значения: api, file.
    # - api - запрашивать конфигурацию из api (адрес в поле api далее)
    # - file - загружать конфигурацию из файла (название файла в поле file далее)
    type = 'api'

    # Эндпоинт для получения конфигурации от конфигуратора. Обязательно, если выставлен source = 'api'
    path = 'https://configurator.robotrade.io/binance/testing?only_new=false'

    # Путь до файла файла, из которого загружается конфигурация. Обязательно, если выставлен source = 'file'
#    path = 'default_config.json'